import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'flex-start',
    alignItems: 'center',
    backgroundColor: 'black',
    paddingTop: '25%',
    paddingBottom: '10%',
  },
  rowContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 20,
    flexWrap: 'wrap',
  },
  title: {
    margin: 10,
    marginBottom: '5%',
    color: 'white',
    fontSize: 18,
  },
  longButton: {
    width: '80%',
    height: 50,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    color: 'black',
    borderRadius: 25,
    margin: 10,
    marginTop: '5%',
  },
  buttonText: {
    color: 'white',
    fontSize: 13,
    fontWeight: '600',
    margin: 10,
  },
  longButtonText: {
    color: 'black',
    fontSize: 13,
    fontWeight: '500',
    margin: 10,
  },
  text: {
    color: 'white',
    fontSize: 13,
    margin: 5,
  },
  textInput: {
    width: '70%',
    height: 40,
    color: 'white',
    margin: 10,
    padding: 5,
    borderStyle: 'solid',
    borderColor: 'white',
    borderWidth: 1,
    borderRadius: 5,
  },
  thumbnail: {
    width: 150,
    height: 150,
  },
  image: {
    width: 300,
    height: 300,
    marginBottom: 10,
  },
  label: {
    width: '70%',
    color: 'white',
    fontSize: 10,
    textAlign: 'left',
    padding: 5,
  },
  error: {
    color: 'red',
    fontSize: 12,
    margin: 10,
  },
});
